variables:
  APP_NAME: drcloud-backend
  IMAGE_TAG_COMMIT: ${CI_REGISTRY_IMAGE}/$CI_COMMIT_REF_NAME:${CI_COMMIT_SHA}
  IMAGE_TAG_LATEST: ${CI_REGISTRY_IMAGE}/$CI_COMMIT_REF_NAME:latest
  DOCKERFILE: ci-cd/${CI_ENVIRONMENT_NAME}/Dockerfile
  DIR_HELMCHART: /home/deploy/helmchart-drcloud
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUILDKIT: 1

stages:
    - build
    - deploy

########## k8s
build_staging:
  environment: staging
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: build
  tags:
    - docker
    - build
    - non-prod
  only:
    - staging
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  script:
    - docker build -f $DOCKERFILE --cache-from $IMAGE_TAG_LATEST --build-arg BUILDKIT_INLINE_CACHE=1 --tag $IMAGE_TAG_COMMIT .
    - docker tag $IMAGE_TAG_COMMIT $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG_COMMIT
    - docker push $IMAGE_TAG_LATEST

deploy_staging:
  environment: staging
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: deploy
  only:
    - staging
  tags:
    - shell
    - non-prod
    - k8s
  script:
    - cd ${DIR_HELMCHART}
    - git fetch
    - git reset --hard origin/main
    - sudo helm upgrade -i $APP_NAME applications/$APP_NAME -f applications/envValues/valuesStg.yaml -n $CI_ENVIRONMENT_NAME --create-namespace --set $APP_NAME.version=$CI_COMMIT_SHA
  when: on_success

################
