//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thucook.Commons.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thucook.Commons.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment at {0} at {1} has been approved.
        /// </summary>
        public static string ApproveAppointmentBody {
            get {
                return ResourceManager.GetString("ApproveAppointmentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment has been approved.
        /// </summary>
        public static string ApproveAppointmentTitle {
            get {
                return ResourceManager.GetString("ApproveAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient {0} has canceled apointment at {1}. Reason: {2}.
        /// </summary>
        public static string CancelAppoinmentBody {
            get {
                return ResourceManager.GetString("CancelAppoinmentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient has canceled appointment.
        /// </summary>
        public static string CancelAppoinmentTitle {
            get {
                return ResourceManager.GetString("CancelAppoinmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment at {0} at {1} has been canceled. Reason: {2}.
        /// </summary>
        public static string CancelAppointmentByClinicBody {
            get {
                return ResourceManager.GetString("CancelAppointmentByClinicBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment has been canceled.
        /// </summary>
        public static string CancelAppointmentByClinicTitle {
            get {
                return ResourceManager.GetString("CancelAppointmentByClinicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment at {0} has been changed as follow: at location {1} at {2} by doctor {3}..
        /// </summary>
        public static string ChangeAppointmentBody {
            get {
                return ResourceManager.GetString("ChangeAppointmentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment detail change.
        /// </summary>
        public static string ChangeAppointmentTitle {
            get {
                return ResourceManager.GetString("ChangeAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been queued at {0}. Note: Patients with scheduled appointments will be given priority when the appointment time arrives..
        /// </summary>
        public static string CreateAppointmentByClinicBody {
            get {
                return ResourceManager.GetString("CreateAppointmentByClinicBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been queued.
        /// </summary>
        public static string CreateAppointmentByClinicTitle {
            get {
                return ResourceManager.GetString("CreateAppointmentByClinicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient {0} has booked a new apointment at {1}.
        /// </summary>
        public static string CreateAppointmentToClinicBody {
            get {
                return ResourceManager.GetString("CreateAppointmentToClinicBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New appointment.
        /// </summary>
        public static string CreateAppointmentToClinicTitle {
            get {
                return ResourceManager.GetString("CreateAppointmentToClinicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new appointment at {0} at {1} has been successfully registered..
        /// </summary>
        public static string CreateAppointmentToPatientBody {
            get {
                return ResourceManager.GetString("CreateAppointmentToPatientBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new appointment.
        /// </summary>
        public static string CreateAppointmentToPatientTitle {
            get {
                return ResourceManager.GetString("CreateAppointmentToPatientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default User.
        /// </summary>
        public static string DefaultUser {
            get {
                return ResourceManager.GetString("DefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re invited to join {0} on Dr.Cloud.
        /// </summary>
        public static string InviteUserSubject {
            get {
                return ResourceManager.GetString("InviteUserSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTemplates/invite-user.html.
        /// </summary>
        public static string InviteUserTemplatePath {
            get {
                return ResourceManager.GetString("InviteUserTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drcloud.vn: Your Dr.Cloud app reset password code is {0}.
        /// </summary>
        public static string ResetPasswordCodeSMS {
            get {
                return ResourceManager.GetString("ResetPasswordCodeSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string ResetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTemplates/forgot-password.html.
        /// </summary>
        public static string ResetPasswordEmailTemplatePath {
            get {
                return ResourceManager.GetString("ResetPasswordEmailTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drcloud.vn: Your Dr.Cloud app verification code is {0}.
        /// </summary>
        public static string VerificationCodeSMS {
            get {
                return ResourceManager.GetString("VerificationCodeSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Dr.Cloud! Verify Your Email.
        /// </summary>
        public static string VerifyEmailSubject {
            get {
                return ResourceManager.GetString("VerifyEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTemplates/verify-email.html.
        /// </summary>
        public static string VerifyEmailTemplatePath {
            get {
                return ResourceManager.GetString("VerifyEmailTemplatePath", resourceCulture);
            }
        }
    }
}
